services:
  postgres:
    image: postgres:16
    container_name: zaping-postgres

    restart: always

    environment:
      POSTGRES_USER: zaping
      POSTGRES_PASSWORD: zaping123
      POSTGRES_DB: zaping_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: